IS_DEBUG = True

BAUD_RATE = 115200

RESERVOIR_NAMES = ["None", "1", "2", "3", "4"]
RESERVOIR_INDEX = dict(zip(RESERVOIR_NAMES, range(5)))
CSV_LEN = 3
OUT_DIR = './output/'

FLOW_RATE_MAX = 80.0
DURATION_MAX = 86_400_000

INTERVAL = 500

TABLE_COL = CSV_LEN + 1
TABLE_WID = 128
STATUS_DONE = "done"
STATUS_PENDING = ""
STATUS_RUNNING = "running"
STATUS_ERROR = "error"
