name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Print version of pythons
        run: |
          python3 --version
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Install pylint
        run: |
          pip install pylint
      - name: Run pylint
        run: |
          pylint ./main.py
          pylint ./canvas/canvas.py
          pylint ./log/log.py
          pylint ./port/port.py
          pylint ./table/table.py
